version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    versioning-strategy: increase # Stategy that'll increase the version number in package.json instead of the package-lock.json
    reviewers:
          - "wiris/integrations"
    commit-message:
          prefix: "npm prod" # Prefix to PR title in updating dependencies
          prefix-development: "npm dev" # Prefix to PR title in updating devDependencies
          include: "scope" # It'll include all the reviews and changes proposal
    labels:
          - "type:dependencies"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "stable"
    labels:
          - "type:dependencies"
    commit-message:
          prefix: "st:npm prod"
          prefix-development: "st:npm dev"
          include: "scope"
