import { serializeHtmlToXml } from "./mathml"; // adjust the import path as needed

describe("serializeHtmlToXml", () => {
  const testCases = [
    `<math />`,
    `<math><mn>10</mn></math>`,
    `<math><mi>x</mi></math>`,
    `<math><mn>4</mn><mi>x</mi></math>`,
    `<math><mi mathvariant="normal">sin</mi><mi>x</mi></math>`,
    `<math><mn>4</mn><mo>+</mo><mi>x</mi></math>`,
    `<math><mn>3</mn><mo>&le;</mo><mn>8</mn><mo>.</mo><mn>3</mn></math>`,
    `<math><mfrac><mn>1</mn><mn>2</mn></mfrac></math>`,
    `<math><mfrac bevelled="true"><mn>2</mn><mn>4</mn></mfrac></math>`,
    `<math><mfrac><mrow><mo>-</mo><mi>x</mi></mrow><mn>2</mn></mfrac></math>`,
    `<math><msup><mi>x</mi><mn>2</mn></msup><mo>-</mo><mn>1</mn></math>`,
    `<math><msub><mi>A</mi><mi>j</mi></msub></math>`,
    `<math><msqrt><mi>x</mi></msqrt></math>`,
    `<math><mroot><mn>8</mn><mn>3</mn></mroot><mo>=</mo><mn>2</mn></math>`,
    `<math><mfenced><mrow><mn>1</mn><mo>,</mo><mn>2</mn></mrow></mfenced></math>`,
    `<math><mfenced open="|" close="|"><mrow><mi>x</mi><mo>-</mo><mn>1</mn></mrow></mfenced><mo>&lt;</mo><mi>&epsi;</mi></math>`,
    `<math><mo>&#177;</mo><mo>&#8734;</mo></math>`,
    `<math><mo>&#8709;</mo><mo>=</mo><mo>{</mo><mo>&#160;</mo><mo>}</mo></math>`,
    `<math><mi>A</mi><mo>&#8745;</mo><mi>B</mi><mo>&#8746;</mo><mi>C</mi></math>`,
    `<math><msub><mi>a</mi><mn>1</mn></msub><mo>&#215;</mo><msub><mi>a</mi><mn>2</mn></msub></math>`,
    `<math><mn>4</mn><mo>∈</mo><mfenced open="{" close="}"><mrow><mn>2</mn><mo>,</mo><mn>4</mn><mo>,</mo><mn>6</mn></mrow></mfenced></math>`,
    `<math><msup><mfenced open="{" close="}"><mrow><mfrac><mn>1</mn><mn>2</mn></mfrac><mfenced><mrow><msup><mi>x</mi><mn>4</mn></msup><mo>-</mo><mn>3</mn></mrow></mfenced></mrow></mfenced><mfrac><mn>1</mn><mn>2</mn></mfrac></msup></math>`,
    `<math><mi>f</mi><mfenced><mi>x</mi></mfenced><mo>=</mo><msup><mi>x</mi><mn>2</mn></msup><mo>+</mo><mn>1</mn><mspace linebreak="newline"/><mi>f</mi><mo>'</mo><mo>(</mo><mi>x</mi><mo>)</mo><mo>=</mo><mn>2</mn><mi>x</mi></math>`,
    `<math><mi mathvariant="bold">z</mi><mo>=</mo><mi mathvariant="bold">u</mi><mo>+</mo><mi mathvariant="bold">v</mi></math>`,
    `<math><mn>1</mn><mo mathcolor="#FF0000">+</mo><mn>2</mn><mo mathcolor="#0000FF">=</mo><mn>3</mn></math>`,
    `<math><mn mathvariant="bold">4</mn><mi mathvariant="normal">x</mi><mo>+</mo><mn mathvariant="bold">2</mn><mi mathvariant="normal">y</mi></math>`,
    `<math style="font-size:24px"><mn mathvariant="italic" mathcolor="#007F00">2</mn><mo mathcolor="#007F00">-</mo><mfrac mathcolor="#007F00"><mn mathvariant="italic">1</mn><mn mathvariant="italic">3</mn></mfrac></math>`,
    `<math style="font-family:'Times New Roman'"><mi>f</mi><mo>'</mo><mo>(</mo><mi>x</mi><mo>)</mo><mo>=</mo><mstyle displaystyle="false"><mfrac><mn>1</mn><mn>2</mn></mfrac></mstyle><msup><mi>x</mi><mn>2</mn></msup></math>`,
    `<math style="font-family:'Courier New'"><msup><mi>a</mi><mn>2</mn></msup><mo>-</mo><msup><mi>b</mi><mn>2</mn></msup></math>`,
    `<math><mi>a</mi><mo>&#8658;</mo><mi>b</mi></math>`,
    `<math><mi>x</mi><mover><mo>&#8614;</mo><mtext>maps&#160;to</mtext></mover><mi>y</mi></math>`,
    `<math><msub><mi>a</mi><mn>1</mn></msub><mo>&#215;</mo><mo>&#8943;</mo><mo>&#215;</mo><msub><mi>a</mi><mi>n</mi></msub></math>`,
    `<math><mover><mrow><mi>A</mi><mi>B</mi></mrow><mo>&#8640;</mo></mover><mo>=</mo><mo>-</mo><mover><mrow><mi>B</mi><mi>A</mi></mrow><mo>&#8640;</mo></mover></math>`,
    `<math><mi>A</mi><munderover><mo>&#x2942;</mo><mrow><mi>r</mi><mi>e</mi><mi>l</mi><mi>a</mi><mi>t</mi><mi>i</mi><mi>o</mi><mi>n</mi><mo>&#xA0;</mo><mn>2</mn></mrow><mrow><mi>r</mi><mi>e</mi><mi>l</mi><mi>a</mi><mi>t</mi><mi>i</mi><mi>o</mi><mi>n</mi><mo>&#xA0;</mo><mn>1</mn></mrow></munderover><mi>B</mi></math>`,
    `<math><mn>1</mn><mo>+</mo><mn>2</mn><mo>Ã—</mo><mn>3</mn><mo>-</mo><mn>4</mn><mo>Ã·</mo><mn>5</mn></math>`,
    `<math><mn>8</mn><mo>Â±</mo><mn>0</mn><mo>.</mo><mn>001</mn></math>`,
    `<math><mi>f</mi><mo>*</mo><mo>(</mo><mi>x</mi><mo>)</mo></math>`,
    `<math><mo>(</mo><mi>f</mi><mo>&#8728;</mo><mi>g</mi><mo>)</mo><mo>(</mo><mi>x</mi><mo>Â·</mo><mi>y</mi><mo>)</mo></math>`,
    `<math><mn>2</mn><mi>p</mi><msup><mi>r</mi><mn>2</mn></msup></math>`,
    `<math><mn>15</mn><mo>Â°</mo><mn>30</mn><mo>'</mo><mn>60</mn><mo>'</mo><mo>'</mo></math>`,
    `<math><mi>f</mi><mo>'</mo><mo>(</mo><mi>x</mi><mo>)</mo><mi>g</mi><mo>(</mo><mi>x</mi><mo>)</mo><mo>+</mo><mi>f</mi><mo>(</mo><mi>x</mi><mo>)</mo><mi>g</mi><mo>'</mo><mo>(</mo><mi>x</mi><mo>)</mo></math>`,
    `<math><mi>x</mi><mo>+</mo><mn>1</mn><mo>=</mo><mn>1</mn><mo>-</mo><mi>x</mi></math>`,
    `<math><mi>A</mi><mo>â‰¡</mo><mi>B</mi></math>`,
    `<math><mn>4</mn><mo>.</mo><mn>99</mn><mo>&sim;</mo><mn>5</mn></math>`,
    `<math><mi>Ï€</mi><mo>â‰ˆ</mo><mn>3</mn><mo>.</mo><mn>1415</mn></math>`,
    `<math><mn>0</mn><mo>â‰¤</mo><mi>x</mi><mo>,</mo><mo>&nbsp;</mo><mn>0</mn><mo>&LessSlantEqual;</mo><mi>x</mi></math>`,
    `<math><mn>5</mn><mo>&lneq;</mo><mn>6</mn></math>`,
    `<math><mi>x</mi><mo>âˆˆ</mo><mi>A</mi><mo>âˆ©</mo><mi>B</mi></math>`,
    `<math><mo>{</mo><mn>2</mn><mo>,</mo><mn>4</mn><mo>}</mo><mo>âŠ‚</mo><mo>{</mo><mn>1</mn><mo>,</mo><mn>2</mn><mo>,</mo><mn>3</mn><mo>,</mo><mn>4</mn><mo>}</mo></math>`,
    `<math><mo>âˆ€</mo><mi>Îµ</mi><mo>âˆƒ</mo><mi>Î´</mi></math>`,
    `<math><mo>Â¬</mo><mi>p</mi><mo>âˆ¨</mo><mi>p</mi></math>`,
    `<math><mo>(</mo><mi>a</mi><mo>âˆ¨</mo><mi>b</mi><mo>)</mo><mo>âˆ§</mo><mo>(</mo><mi>c</mi><mo>âˆ¨</mo><mi>d</mi><mo>)</mo></math>`,
    `<math><mo>∠</mo><mi>a</mi></math>`,
    `<math><mi>r</mi><mo>âˆ¥</mo><mi>s</mi></math>`,
    `<math><mi>r</mi><mo>âŠ¥</mo><mi>s</mi></math>`,
    `<math><mn>3</mn><mo>&in;</mo><mi mathvariant="normal">&naturals;</mi></math>`,
    `<math><mi>&pi;</mi><mo>&in;</mo><mi mathvariant="normal">&Ropf;</mi><mo>&Backslash;</mo><mi mathvariant="normal">&Qopf;</mi></math>`,
    `<math><mo>&realpart;</mo><mo>(</mo><mn>4</mn><mo>+</mo><mn>3</mn><mi>i</mi><mo>)</mo><mo>=</mo><mn>4</mn></math>`,
    `<math><mi mathvariant="double-struck">D</mi><mo>&#x000A0;</mo><mo>=</mo><mo>&#x000A0;</mo><mo>{</mo><mo>&#x000A0;</mo><mi>z</mi><mo>&#x02208;</mo><mi mathvariant="normal">&#x02102;</mi><mo>&#x000A0;</mo><mo>&#x000A0;</mo><mo>:</mo><mo>&#x000A0;</mo><mo>&#x02009;</mo><mo>|</mo><mi>z</mi><mo>|</mo><mo>&lt;</mo><mn>1</mn><mo>&#x000A0;</mo><mo>}</mo></math>`,
    `<math><msub><mi mathvariant="double-struck">A</mi><mi mathvariant="normal">&#x0211A;</mi></msub><mo>=</mo><mi mathvariant="normal">&#x0211A;</mi><mo>&#x000A0;</mo><msub><mo>&#x02297;</mo><mi mathvariant="normal">&#x02124;</mi></msub><mo>&#x000A0;</mo><msub><mi mathvariant="double-struck">A</mi><mi mathvariant="normal">&#x02124;</mi></msub></math>`,
    `<math><mi mathvariant="script">H</mi><mo>=</mo><munder><mo>&#x02211;</mo><mi>i</mi></munder><msub><mover><mi>q</mi><mo>&#x002D9;</mo></mover><mi>i</mi></msub><mfrac><mrow><mo>&#x02202;</mo><mi mathvariant="script">L</mi></mrow><mrow><mo>&#x02202;</mo><msub><mover><mi>q</mi><mo>&#x002D9;</mo></mover><mi>i</mi></msub></mrow></mfrac><mo>-</mo><mi mathvariant="script">L</mi></math>`,
    `<math><msub><mi mathvariant="script">R</mi><mi mathvariant="script">Q</mi></msub><mo>&#x000A0;</mo><mo>&#x02245;</mo><mo>&#x000A0;</mo><msub><mi>T</mi><mi mathvariant="script">Q</mi></msub></math>`,
    `<math><mi mathvariant="fraktur">p</mi><mo>&#x000A0;</mo><mo>&#x02283;</mo><mo>&#x000A0;</mo><mi mathvariant="fraktur">ab</mi><mo>&#x000A0;</mo><mo>&#x021D2;</mo><mi mathvariant="fraktur">p</mi><mo>&#x02283;</mo><mi mathvariant="fraktur">a</mi><mo>&#x000A0;</mo><mo>&#x02228;</mo><mo>&#x000A0;</mo><mi mathvariant="fraktur">p</mi><mo>&#x000A0;</mo><mo>&#x02283;</mo><mi mathvariant="fraktur">b</mi></math>`,
    `<math><mi mathvariant="script">B</mi><mo>=</mo><mo>{</mo><msub><mi>B</mi><mi>&#x003B1;</mi></msub><mo>&#x02208;</mo><mi mathvariant="script">T</mi><mo>&#x0200A;</mo><mo>|</mo><mo>&#x0200A;</mo><mi>U</mi><mo>=</mo><mo largeop="true">&#x0222A;</mo><msub><mi>B</mi><mi>&#x003B1;</mi></msub><mo>&#x02200;</mo><mi>U</mi><mo>&#x02208;</mo><mi mathvariant="script">T</mi><mo>}</mo></math>`,
    `<math><mi>A</mi><mo>&CirclePlus;</mo><mi>B</mi></math>`,
    `<math><mi>i</mi><mo>←</mo><mi>i</mi><mo>+</mo><mn>1</mn></math>`,
    `<math><mi>x</mi><mo>&map;</mo><msup><mi>x</mi><mn>2</mn></msup><mo>+</mo><mn>1</mn></math>`,
    `<math><mi>x</mi><mo>&lt;</mo><mn>3</mn><mo>âˆ§</mo><mi>x</mi><mo>&Implies;</mo><mo>-</mo><mn>2</mn><mo>â‡’</mo><mi>x</mi><mo>â©½</mo><mo>-</mo><mn>2</mn></math>`,
    `<math><mo>&#9633;</mo><mo>&#8800;</mo><mo>&#9675;</mo></math>`,
    `<math><mi>a</mi><mo>&#8742;</mo><mi>b</mi><mo>,</mo><mo>&#160;</mo><mi>A</mi><mo>&#8716;</mo><mi>x</mi></math>`,
    `<math><mi mathvariant="normal">cos</mi><mo>(</mo><mi>&alpha;</mi><mo>&pm;</mo><mi>&beta;</mi><mo>)</mo><mo>=</mo><mi mathvariant="normal">cos</mi><mi>&alpha;</mi><mi mathvariant="normal">cos</mi><mi>&beta;</mi><mo>&mp;</mo><mi mathvariant="normal">sin</mi><mi>&alpha;</mi><mi mathvariant="normal">sin</mi><mi>&beta;</mi></math>`,
    `<math><mi mathvariant="normal">sin</mi><mo>(</mo><mi>&theta;</mi><mo>+</mo><mfrac><mi>&pi;</mi><mn>2</mn></mfrac><mo>)</mo><mo>=</mo><mi mathvariant="normal">cos</mi><mi>&theta;</mi></math>`,
    `<math><mi mathvariant="normal">Î©</mi><mo>=</mo><mfrac><mi mathvariant="normal">V</mi><mi mathvariant="normal">A</mi></mfrac></math>`,
    `<math><mi>Ï†</mi><mo>(</mo><mi>x</mi><mo>)</mo><mo>+</mo><mi>Ïˆ</mi><mo>(</mo><mi>y</mi><mo>)</mo><mo>+</mo><mi>Î¾</mi><mo>(</mo><mi>z</mi><mo>)</mo></math>`,
    `<math><mfenced open="[" close="]"><mtable><mtr><mtd><mn>1</mn></mtd></mtr><mtr><mtd><mn>2</mn></mtd></mtr></mtable></mfenced></math>`,
    `<math><mfenced><mtable><mtr><mtd><mi>x</mi></mtd></mtr><mtr><mtd><mi>y</mi></mtd></mtr></mtable></mfenced></math>`,
    `<math><mfenced><mtable><mtr><mtd><mn>1</mn></mtd><mtd><mo>&nbsp;</mo></mtd><mtd><mo>&nbsp;</mo></mtd></mtr><mtr><mtd><mo>&nbsp;</mo></mtd><mtd><mn>1</mn></mtd><mtd><mo>&nbsp;</mo></mtd></mtr><mtr><mtd><mo>&nbsp;</mo></mtd><mtd><mo>&nbsp;</mo></mtd><mtd><mn>1</mn></mtd></mtr></mtable></mfenced></math>`,
    `<math><mfenced open="|" close="|"><mtable><mtr><mtd><mi mathvariant="normal">sin</mi><mo>(</mo><mi>x</mi><mo>)</mo></mtd><mtd><mi mathvariant="normal">cos</mi><mo>(</mo><mi>x</mi><mo>)</mo></mtd></mtr><mtr><mtd><mo>-</mo><mi mathvariant="normal">cos</mi><mo>(</mo><mi>x</mi><mo>)</mo></mtd><mtd><mi mathvariant="normal">sin</mi><mo>(</mo><mi>x</mi><mo>)</mo></mtd></mtr></mtable></mfenced><mo>=</mo><mn>1</mn></math>`,
    `<math><mfenced open="{" close=""><mtable><mtr><mtd><mi>x</mi><mo>+</mo><mn>1</mn></mtd></mtr><mtr><mtd><mi>x</mi><mo>-</mo><mn>1</mn></mtd></mtr></mtable></mfenced></math>`,
    `<math><mi>f</mi><mo>(</mo><mi>x</mi><mo>)</mo><mo>=</mo><mfenced open="{" close=""><mtable columnspacing="1.4ex" columnalign="left"><mtr><mtd><mi>x</mi><mo>,</mo></mtd><mtd><mtext>if&#160;</mtext><mi>x</mi><mo>&#10877;</mo><mn>0</mn></mtd></mtr><mtr><mtd><mi mathvariant="normal">sin</mi><mo>(</mo><mi>x</mi><mo>)</mo><mo>,</mo></mtd><mtd><mtext>if&#160;</mtext><mi>x</mi><mo>&#62;</mo><mn>0</mn></mtd></mtr></mtable></mfenced></math>`,
    `<math><mtable columnspacing="2px" columnalign="right center left"><mtr><mtd><msup><mi>x</mi><mn>5</mn></msup><mo>+</mo><mn>1</mn></mtd><mtd><mo>=</mo></mtd><mtd><msup><mi>x</mi><mn>4</mn></msup><mo>-</mo><mi>y</mi></mtd></mtr><mtr><mtd><mi>x</mi></mtd><mtd><mo>=</mo></mtd><mtd><mstyle displaystyle="false"><mfrac><mn>1</mn><mn>2</mn></mfrac></mstyle><mi>y</mi><mo>+</mo><mn>3</mn></mtd></mtr></mtable></math>`,
    `<math><mtable columnspacing="2px" columnalign="right center left"><mtr><mtd><mo>(</mo><mn>2</mn><mo>+</mo><mn>3</mn><msup><mo>)</mo><mn>2</mn></msup></mtd><mtd><mo>=</mo></mtd><mtd><mo>(</mo><mn>5</mn><msup><mo>)</mo><mn>2</mn></msup></mtd></mtr><mtr><mtd><mo>&#160;</mo></mtd><mtd><mo>=</mo></mtd><mtd><mn>25</mn></mtd></mtr></mtable></math>`,
    `<math><mstyle displaystyle="false"><mfrac bevelled="true"><mn>1</mn><mn>2</mn></mfrac></mstyle><mo>&#160;</mo><mn>5</mn></math>`,
    `<math><mn>3</mn><mo>+</mo><mfrac><mn>1</mn><mrow><mn>7</mn><mo>+</mo><mfrac><mn>1</mn><mrow><mo>.</mo><mo>.</mo><mo>.</mo></mrow></mfrac></mrow></mfrac></math>`,
    `<math><msqrt><mn>1</mn><mo>-</mo><mi>x</mi></msqrt></math>`,
    `<math><mroot><mn>2</mn><mn>3</mn></mroot></math>`,
    `<math><mroot><mrow><msup><mi>x</mi><mi>n</mi></msup><mo>+</mo><msup><mi>y</mi><mi>n</mi></msup></mrow><mi>n</mi></mroot></math>`,
    `<math><mroot><mi>a</mi><mrow><mi>n</mi><mo>+</mo><mn>1</mn></mrow></mroot></math>`,
    `<math><mo>(</mo><mi mathvariant="normal">OH</mi><msubsup><mo>)</mo><mn>4</mn><mo>-</mo></msubsup></math>`,
    `<math><msubsup><mi>V</mi><mi>m</mi><mi>n</mi></msubsup><mo>=</mo><mfrac><mrow><mi>m</mi><mo>!</mo></mrow><mrow><mfenced><mrow><mi>m</mi><mo>-</mo><mi>n</mi></mrow></mfenced><mo>!</mo></mrow></mfrac><mspace linebreak="newline"/><msubsup><mi>V</mi><mn>3</mn><mn>2</mn></msubsup><mo>=</mo><mn>6</mn></math>`,
    `<math><mmultiscripts><mi mathvariant="normal">U</mi><mprescripts/><mn>92</mn><mn>235</mn></mmultiscripts></math>`,
    `<math><mo>(</mo><mi>A</mi><mi>B</mi><msubsup><mo>)</mo><mi>i</mi><mi>j</mi></msubsup><mo>=</mo><msubsup><mi>A</mi><mi>i</mi><mi>k</mi></msubsup><msubsup><mi>B</mi><mi>k</mi><mi>j</mi></msubsup></math>`,
    `<math><mi mathvariant="normal">Zn</mi><mo>+</mo><mn>2</mn><msup><mi mathvariant="normal">H</mi><mo>+</mo></msup><mo>â†’</mo><msup><mi mathvariant="normal">Zn</mi><mrow><mn>2</mn><mo>+</mo></mrow></msup><mo>+</mo><msub><mi mathvariant="normal">H</mi><mn>2</mn></msub></math>`,
    `<math><mover><mrow><mn>3</mn><mo>+</mo><mn>5</mn></mrow><mn>8</mn></mover></math>`,
    `<math><munder><mrow><mn>3</mn><msup><mi>x</mi><mn>2</mn></msup><mo>-</mo><mn>2</mn></mrow><mrow><mo>(</mo><mn>2</mn><mo>&nbsp;</mo><mi mathvariant="normal">degree</mi><mo>)</mo></mrow></munder></math>`,
    `<math><munder><munder><mrow><mn>1</mn><mo>+</mo><mn>2</mn></mrow><mo>&#9183;</mo></munder><mn>3</mn></munder></math>`,
    `<math><mover><mover><mrow><munder><munder><mrow><mn>1</mn><mo>+</mo><mn>2</mn></mrow><mo>&#9183;</mo></munder><mn>3</mn></munder><mo>+</mo><mn>3</mn></mrow><mo>&#9182;</mo></mover><mn>5</mn></mover></math>`,
    `<math><mfenced open="&lt;" close="&#62;"><mfrac><mn>1</mn><mn>2</mn></mfrac></mfenced></math>`,
    `<math><mstyle displaystyle="false"><mfrac><mn>4</mn><mn>3</mn></mfrac></mstyle><mo>=</mo><mn>1</mn><mo>'</mo><mover><mn>3</mn><mo>&#9180;</mo></mover></math>`,
    `<math><mover><mi>u</mi><mo>&#8594;</mo></mover><mo>+</mo><mover><mi>v</mi><mo>&#8594;</mo></mover></math>`,
    `<math><mover><mrow><mi>x</mi><mo>+</mo><mover><mi>y</mi><mo>&#175;</mo></mover></mrow><mo>&#175;</mo></mover></math>`,
    `<math><msup><mi>x</mi><menclose notation="circle"><mn>5</mn></menclose></msup><mo>-</mo><msup><mi>x</mi><mn>2</mn></msup><mo>+</mo><menclose notation="box"><mn>3</mn></menclose></math>`,
    `<math><mfrac><mrow><mi>a</mi><mo>&#183;</mo><menclose mathcolor="#FF0000" notation="updiagonalstrike"><mi mathcolor="#191919">b</mi></menclose><mo>&#183;</mo><menclose mathcolor="#0000FF" notation="downdiagonalstrike"><mi mathcolor="#191919">d</mi></menclose><mo>&#183;</mo><menclose mathcolor="#007F00" notation="verticalstrike"><mi mathcolor="#191919">e</mi></menclose></mrow><mrow><menclose mathcolor="#FF0000" notation="updiagonalstrike"><mi mathcolor="#191919">b</mi></menclose><mo>&#183;</mo><mi>c</mi><mo>&#183;</mo><menclose mathcolor="#0000FF" notation="downdiagonalstrike"><mi mathcolor="#191919">d</mi></menclose><mo>&#183;</mo><mi>f</mi><mo>&#183;</mo><menclose mathcolor="#007F00" notation="verticalstrike"><mi mathcolor="#191919">e</mi></menclose></mrow></mfrac></math>`,
    `<math><munderover><mo>âˆ‘</mo><mrow><mi>i</mi><mo>=</mo><mn>1</mn></mrow><mi>n</mi></munderover><msup><mn>2</mn><mi>i</mi></msup></math>`,
    `<math><munder><munder><mo>âˆ</mo><mrow><mi>p</mi><mo>(</mo><mi>Î±</mi><mo>)</mo><mo>=</mo><mn>0</mn></mrow></munder><mrow><mi>q</mi><mo>(</mo><mi>Î²</mi><mo>)</mo><mo>=</mo><mn>0</mn></mrow></munder><mo>(</mo><mi>Î±</mi><mo>-</mo><mi>Î²</mi><mo>)</mo></math>`,
    `<math><msubsup><mo>∑</mo><mrow><mi>i</mi><mo>=</mo><mn>1</mn></mrow><mo>∞</mo></msubsup><mfrac><mn>1</mn><msup><mi>i</mi><mn>2</mn></msup></mfrac></math>`,
    `<math><munder><mo largeop="true">&cap;</mo><mrow><mi>x</mi><mo>&isin;</mo><mi>A</mi></mrow></munder><mi>A</mi></math>`,
    `<math><msubsup><mo>∫</mo><mn>0</mn><mn>1</mn></msubsup><msup><mi>x</mi><mn>2</mn></msup><mo>-</mo><mn>2</mn><mi>d</mi><mi>x</mi></math>`,
    `<math><msub><mo>∫</mo><mi>w</mi></msub><mi>d</mi><mi>f</mi><mo>=</mo><msub><mo>∫</mo><mrow><mo>∂</mo><mi>w</mi></mrow></msub><mi>f</mi></math>`,
    `<math><mfrac><mrow><msup><mo>∂</mo><mn>2</mn></msup><mi>f</mi></mrow><mrow><mo>∂</mo><mi>x</mi><mo>∂</mo><mi>y</mi></mrow></mfrac></math>`,
    `<math><mfrac><mrow><mi>d</mi><mi mathvariant="normal">sin</mi><mo>(</mo><mi>x</mi><mo>)</mo></mrow><mrow><mi>d</mi><mi>x</mi></mrow></mfrac><mo>=</mo><mo>-</mo><mi mathvariant="normal">cos</mi><mo>(</mo><mi>x</mi><mo>)</mo></math>`,
    `<math><munder><mi mathvariant="normal">lim</mi><mrow><mi>n</mi><mo>→</mo><mo>∞</mo></mrow></munder><msup><mfenced><mrow><mn>1</mn><mo>+</mo><mfrac><mn>1</mn><mi>n</mi></mfrac></mrow></mfenced><mi>n</mi></msup></math>`,
    `<math><munder><mi mathvariant="normal">lim</mi><mrow><mi>x</mi><mo>↗</mo><mi>a</mi></mrow></munder><mo>&nbsp;</mo><mi>f</mi><mo>(</mo><mi>a</mi><mo>)</mo></math>`,
    `<math><mo>∆</mo><mi>u</mi><mo>=</mo><msub><mi>u</mi><mrow><mi>x</mi><mi>x</mi></mrow></msub><mo>+</mo><msub><mi>u</mi><mrow><mi>y</mi><mi>y</mi></mrow></msub><mo>+</mo><msub><mi>u</mi><mrow><mi>z</mi><mi>z</mi></mrow></msub></math>`,
    `<math><msub><mo>&oint;</mo><mrow><msup><mi>x</mi><mn>2</mn></msup><mo>+</mo><msup><mi>y</mi><mn>2</mn></msup><mo>=</mo><mi>r</mi></mrow></msub><mi>g</mi><mo>(</mo><mi>x</mi><mo>,</mo><mi>y</mi><mo>)</mo><mi>d</mi><mi>x</mi><mo>+</mo><mi>h</mi><mo>(</mo><mi>x</mi><mo>,</mo><mi>y</mi><mo>)</mo><mi>d</mi><mi>y</mi></math>`,
    `<math><msub><mi>log</mi><mn>10</mn></msub><mi>x</mi></math>`,
    `<math><mstack charalign="center" stackalign="right"><mscarries><mn>1</mn><none/></mscarries><mn>35</mn><msrow><mo>+</mo><mn>89</mn></msrow><msline/><mn>124</mn></mstack></math>`,
    `<math><mstack charalign="center" stackalign="right"><mscarries><mn>1</mn><none/></mscarries><mn>24</mn><msrow><mo>&#215;</mo><mn>23</mn></msrow><msline/><mscarries><mn>1</mn><none/><none/></mscarries><mn>72</mn><msrow><mn>48</mn><none/></msrow><msline/><mn>552</mn></mstack><mspace linebreak="newline"/></math>`,
    `<math><mlongdiv charalign="center" charspacing="0px" stackalign="left"><mstack charalign="center" stackalign="right"><mn>5</mn></mstack><mn>69</mn><msgroup><msrow><none/><mn>346</mn></msrow><msrow><mo>-</mo><mn>30</mn></msrow><msline length="3"/><msrow><none/><none/><mn>46</mn></msrow><msrow><none/><mo>-</mo><mn>45</mn></msrow><msline length="3" position="1"/><msrow><none/><none/><none/><mn>1</mn></msrow></msgroup></mlongdiv><mspace linebreak="newline"/></math>`,
    `<math><mlongdiv longdivstyle="shortstackedrightright" charalign="center" charspacing="0px" stackalign="left"><mn>7</mn><mn>17</mn><msgroup><mn>123</mn><msrow><mo>-</mo><mn>7</mn></msrow><msline length="2"/><msrow><none/><mn>53</mn></msrow><msrow><mo>-</mo><mn>49</mn></msrow><msline/><msrow><none/><none/><mn>4</mn></msrow></msgroup></mlongdiv><mspace linebreak="newline"/></math>`,
    `<math><msqrt><msqrt><msqrt><msqrt><msqrt><msqrt><msqrt><msqrt><msqrt><msqrt><msqrt><msqrt><msqrt><msqrt><msqrt><msqrt><msqrt><msqrt><msqrt><mi>x</mi></msqrt></msqrt></msqrt></msqrt></msqrt></msqrt></msqrt></msqrt></msqrt></msqrt></msqrt></msqrt></msqrt></msqrt></msqrt></msqrt></msqrt></msqrt></msqrt></math>`,
    `<math><mfenced open="{" close=""><mtable><mtr><mtd><mn>3</mn><mi>x</mi><mo>+</mo><mn>2</mn><mi>y</mi><mo>-</mo><mi>z</mi><mo>=</mo><mn>1</mn></mtd></mtr><mtr><mtd><mn>5</mn><mi>x</mi><mo>-</mo><mi>y</mi><mo>+</mo><mn>4</mn><mi>z</mi><mo>=</mo><mo>-</mo><mn>4</mn></mtd></mtr><mtr><mtd><mi>x</mi><mo>-</mo><mn>3</mn><mi>y</mi><mo>+</mo><mn>2</mn><mi>z</mi><mo>=</mo><mn>0</mn></mtd></mtr></mtable></mfenced></math>`,
    `<math><mrow><munderover><mmultiscripts><mo>&#x220F;</mo><mmultiscripts><mi>A</mi><mi>&#x03C5;</mi><mi>&#x03C4;</mi><mprescripts /><mi>&#x03C1;</mi><mi>&#x03C3;</mi></mmultiscripts><mmultiscripts><mi>B</mi><mi>&#x03C0;</mi><mi>&#x03BF;</mi><mprescripts /><mi>&#x03BD;</mi><mi>&#x03BE;</mi></mmultiscripts><mprescripts /><mmultiscripts><mi>C</mi><mi>&#x03B4;</mi><mi>&#x03B3;</mi><mprescripts /><mi>&#x03B1;</mi><mi>&#x03B2;</mi></mmultiscripts><mmultiscripts><mi>D</mi><mi>&#x03B8;</mi><mi>&#x03B7;</mi><mprescripts /><mi>&#x03B5;</mi><mi>&#x03B6;</mi></mmultiscripts></mmultiscripts><mmultiscripts><mi>E</mi><mi>&#x03C9;</mi><mi>&#x03C8;</mi><mprescripts /><mi>&#x03D5;</mi><mi>&#x03C7;</mi></mmultiscripts><mmultiscripts><mi>F</mi><mi>&#x03BC;</mi><mi>&#x03BB;</mi><mprescripts /><mi>&#x03B9;</mi><mi>&#x03BA;</mi></mmultiscripts></munderover></mrow></math>`,
    `<math><mtable columnspacing="2px" columnalign="right center left"><mtr><mtd><mo>(</mo><mi>a</mi><mo>+</mo><mi>b</mi><msup><mo>)</mo><mn>2</mn></msup></mtd><mtd><mo>=</mo></mtd><mtd><mo>(</mo><mi>a</mi><mo>+</mo><mi>b</mi><mo>)</mo><mo>(</mo><mi>a</mi><mo>+</mo><mi>b</mi><mo>)</mo></mtd></mtr><mtr><mtd><mo>&#160;</mo></mtd><mtd><mo>=</mo></mtd><mtd><mi>a</mi><mo>(</mo><mi>a</mi><mo>+</mo><mi>b</mi><mo>)</mo><mo>+</mo><mi>b</mi><mo>(</mo><mi>a</mi><mo>+</mo><mi>b</mi><mo>)</mo></mtd></mtr><mtr><mtd><mo>&#160;</mo></mtd><mtd><mo>=</mo></mtd><mtd><msup><mi>a</mi><mn>2</mn></msup><mo>+</mo><mi>a</mi><mi>b</mi><mo>+</mo><mi>b</mi><mi>a</mi><mo>+</mo><msup><mi>b</mi><mn>2</mn></msup></mtd></mtr><mtr><mtd><mo>&#160;</mo></mtd><mtd><mo>=</mo></mtd><mtd><msup><mi>a</mi><mn>2</mn></msup><mo>+</mo><mn>2</mn><mi>a</mi><mi>b</mi><mo>+</mo><msup><mi>b</mi><mn>2</mn></msup></mtd></mtr></mtable></math>`,
    `<math><mfenced><msup><mfenced><msup><mfenced><msup><mfenced><msup><mfenced><msup><mfenced><msup><mfenced><msup><mfenced><msup><mfenced><msup><mfenced><mi mathvariant="normal">O</mi></mfenced><mn>1</mn></msup></mfenced><mn>2</mn></msup></mfenced><mn>3</mn></msup></mfenced><mn>4</mn></msup></mfenced><mn>5</mn></msup></mfenced><mn>6</mn></msup></mfenced><mn>7</mn></msup></mfenced><mn>8</mn></msup></mfenced><mn>9</mn></msup></mfenced></math>`,
    `<math><mtable><mtr><mtd><mn>0</mn></mtd><mtd><mo>&#8592;</mo></mtd><mtd><mn>3</mn></mtd></mtr><mtr><mtd><mo>&#8595;</mo></mtd><mtd><mtable><mtr><mtd/><mtd/></mtr><mtr><mtd/><mtd/></mtr></mtable><mo>&#160;</mo></mtd><mtd><mo>&#8593;</mo></mtd></mtr><mtr><mtd><mn>1</mn></mtd><mtd><mo>&#8594;</mo></mtd><mtd><mn>2</mn></mtd></mtr></mtable><mspace linebreak="newline"/></math>`,
    `<math><mi>f</mi><mo>(</mo><mi>a</mi><mo>,</mo><mi>b</mi><mo>,</mo><mi>c</mi><mo>)</mo><mo>=</mo><mi>a</mi><mi>b</mi><mi>c</mi></math>`,
    `<math><mtext>WIRIS&#xA0;rules</mtext></math>`,
    `<math><mi>x</mi><mo>=</mo><mfrac><mn>1</mn><mn>2</mn></mfrac><mo>+</mo><mfrac><mi>x</mi><mi>n</mi></mfrac><mo>-</mo><mfrac><mrow><mn>2</mn><mi>x</mi><mo>-</mo><mn>1</mn></mrow><mn>2</mn></mfrac></math>`,
    `<math><msqrt><mn>2</mn></msqrt><mo>+</mo><mn>3</mn><msqrt><mi>x</mi></msqrt></math>`,
    `<math><msqrt><mfrac><mi>x</mi><mn>2</mn></mfrac></msqrt><mo>+</mo><msqrt><msup><mi>x</mi><mn>2</mn></msup></msqrt><mo>+</mo><msqrt><msub><mi>x</mi><mi>i</mi></msub></msqrt><mo>+</mo><msqrt><mfenced><mrow><mi>x</mi><mo>-</mo><mn>1</mn></mrow></mfenced></msqrt></math>`,
    `<math><mroot><mn>8</mn><mn>3</mn></mroot><mo>+</mo><mroot><mn>2</mn><mi>n</mi></mroot><mo>+</mo><mroot><mi>x</mi><mrow><mn>2</mn><mi>p</mi></mrow></mroot></math>`,
    `<math><msup><mi>x</mi><mn>2</mn></msup><mo>+</mo><msup><mi>x</mi><mi>n</mi></msup><mo>+</mo><msup><mn>2</mn><mn>3</mn></msup><mo>-</mo><msup><mn>2</mn><mi>n</mi></msup></math>`,
    `<math><msub><mi>x</mi><mi>i</mi></msub><mo>+</mo><msub><mi>x</mi><mn>2</mn></msub><mo>+</mo><msub><mi>x</mi><mi>n</mi></msub></math>`,
    `<math><msubsup><mi>x</mi><mi>n</mi><mi>m</mi></msubsup><mo>+</mo><msubsup><mi>x</mi><mi>i</mi><mi>j</mi></msubsup><mo>+</mo><msubsup><mi>x</mi><mi>t</mi><mi>p</mi></msubsup><mo>+</mo><msubsup><mi>x</mi><mn>2</mn><mn>3</mn></msubsup></math>`,
    `<math><mover><mi>u</mi><mo>&#x2192;</mo></mover><mo>+</mo><mover><mi>k</mi><mo>&#x21C0;</mo></mover><mo>+</mo><mover><mrow><mi>A</mi><mi>B</mi></mrow><mo>&#xAF;</mo></mover></math>`,
    `<math><munderover><mo>&#x2211;</mo><mrow><mi>n</mi><mo>=</mo><mn>0</mn></mrow><mo>&#x221E;</mo></munderover><msub><mi>x</mi><mi>n</mi></msub></math>`,
    `<math><menclose notation="top"><mi>x</mi></menclose><mo>+</mo><menclose notation="updiagonalstrike"><mn>2</mn><mi>n</mi></menclose><mo>+</mo><menclose notation="bottom"><mi>p</mi></menclose></math>`,
    `<math><msubsup><mo>&#x222B;</mo><mn>0</mn><mn>1</mn></msubsup><mi>x</mi><mo>d</mo><mi>x</mi><mo>+</mo><msubsup><mo>&#x222B;</mo><mi>a</mi><mi>b</mi></msubsup><mi>f</mi><mo>(</mo><mi>x</mi><mo>)</mo><mo>d</mo><mi>x</mi></math>`,
    `<math><mi>f</mi><mo>(</mo><mi>x</mi><mo>)</mo><mo>+</mo><mi>f</mi><mo>'</mo><mo>(</mo><mi>a</mi><mo>)</mo><mo>+</mo><mi>g</mi><mo>(</mo><mi>y</mi><mo>)</mo></math>`,
    `<math><mfenced><mrow><msqrt><mi>x</mi></msqrt><mo>-</mo><msqrt><mi>y</mi></msqrt></mrow></mfenced><mfenced><mrow><msup><mi>x</mi><mn>2</mn></msup><mo>-</mo><msup><mi>y</mi><mn>2</mn></msup></mrow></mfenced><mfenced><mrow><msub><mi>x</mi><mi>n</mi></msub><mo>-</mo><msub><mi>x</mi><mi>m</mi></msub></mrow></mfenced></math>`,
    `<math><mfenced><mfrac><mrow><mi>x</mi><mo>+</mo><mn>1</mn></mrow><mfrac><mn>1</mn><mn>2</mn></mfrac></mfrac></mfenced><mo>+</mo><mfenced><mfrac><mrow><mi>x</mi><mo>-</mo><mn>1</mn></mrow><mrow><mi>x</mi><mo>-</mo><mn>2</mn></mrow></mfrac></mfenced></math>`,
    `<math><mfenced><msup><mfenced><msup><mfenced><msup><mfenced><mi>x</mi></mfenced><mn>2</mn></msup></mfenced><mn>3</mn></msup></mfenced><mn>4</mn></msup></mfenced></math>`,
    `<math><mfenced><mfenced open="&lt;" close="&gt;"><mfenced open="[" close="]"><mfenced open="||" close="||"><mfenced open="{" close="}"><mfenced open="&#x230A;" close="&#x230B;"><mfenced open="&#x27E6;" close="&#x27E7;"><mi>x</mi></mfenced></mfenced></mfenced></mfenced></mfenced></mfenced></mfenced><mo>&#xA0;</mo><mo>(</mo><mo>[</mo><mo>|</mo><mo>{</mo><mo>}</mo><mo>|</mo><mo>]</mo><mo>)</mo></math>`,
    `<math><mfenced><mfenced open="|" close="|"><mfenced open="&lt;" close="&gt;"><mfenced open="[" close="]"><mfenced open="||" close="||"><mfenced open="{" close="}"><mfenced open="&#x230A;" close="&#x230B;"><mfenced open="&#x27E6;" close="&#x27E7;"><mfrac><mn>1</mn><mn>2</mn></mfrac></mfenced></mfenced></mfenced></mfenced></mfenced></mfenced></mfenced></mfenced></math>`,
    `<math><mfrac><mrow><mi>f</mi><mo>&#x2218;</mo><mi>g</mi></mrow><mrow><mi>f</mi><mo>&#x2218;</mo><mi>h</mi></mrow></mfrac><mo>&#xA0;</mo><mfrac><mn>1</mn><msqrt><mn>2</mn></msqrt></mfrac><mo>&#xA0;</mo><mfrac><msub><mi>x</mi><mi>j</mi></msub><msup><mi>x</mi><mi>t</mi></msup></mfrac><mo>&#xA0;</mo><mfrac><menclose notation="bottom"><mi>x</mi></menclose><mover><mi>x</mi><mo>&#x2192;</mo></mover></mfrac><mo>&#xA0;</mo><mfrac><mn>1</mn><mover><mi>k</mi><mo>&#x2192;</mo></mover></mfrac><mo>&#xA0;</mo><mfrac><mn>1</mn><mrow><mn>2</mn><mo>.</mo><mover><mn>3</mn><mo>&#x23DC;</mo></mover></mrow></mfrac></math>`,
    `<math><mfrac><mfenced><mfenced open="|" close="|"><mfenced open="&lt;" close="&gt;"><mfenced open="[" close="]"><mfenced open="||" close="||"><mfenced open="{" close="}"><mfenced open="&#x230A;" close="&#x230B;"><mfenced open="&#x2308;" close="&#x2309;"><mrow/></mfenced></mfenced></mfenced></mfenced></mfenced></mfenced></mfenced></mfenced><mfenced><mfenced open="|" close="|"><mfenced open="&lt;" close="&gt;"><mfenced open="[" close="]"><mfenced open="||" close="||"><mfenced open="{" close="}"><mfenced open="&#x230A;" close="&#x230B;"><mfenced open="&#x2308;" close="&#x2309;"><mrow/></mfenced></mfenced></mfenced></mfenced></mfenced></mfenced></mfenced></mfenced></mfrac><mo>&#xA0;</mo><mfrac><mrow><mo>(</mo><mo>|</mo><mo>[</mo><mo>{</mo><mo>}</mo><mo>]</mo><mo>|</mo><mo>)</mo></mrow><mrow><mo>(</mo><mo>|</mo><mo>[</mo><mo>{</mo><mo>}</mo><mo>]</mo><mo>|</mo><mo>)</mo></mrow></mfrac></math>`,
    `<math><msqrt><mi>f</mi><mo>&#x2218;</mo><mi>g</mi></msqrt><mo>&#xA0;</mo><msqrt><msqrt><msqrt><mi>x</mi></msqrt></msqrt></msqrt><mo>&#xA0;</mo><msqrt><msup><mi>x</mi><mi>t</mi></msup></msqrt><mo>&#xA0;</mo></math>`,
    `<math><msqrt><mover><mi>x</mi><mo>&#x2192;</mo></mover></msqrt><mo>&#xA0;</mo><msqrt><mover><mi>t</mi><mo>&#x2192;</mo></mover></msqrt><mo>&#xA0;</mo><msqrt><menclose notation="top"><mi>x</mi></menclose></msqrt><mo>&#xA0;</mo><msqrt><menclose notation="top"><mn>2</mn></menclose></msqrt><mo>&#xA0;</mo><msqrt><mn>2</mn><mo>.</mo><mover><mn>3</mn><mo>&#x23DC;</mo></mover></msqrt></math>`,
    `<math><mroot><mn>2</mn><mrow><mi>j</mi><mi>j</mi><mi>j</mi><mi>j</mi></mrow></mroot><mo>&#xA0;</mo><mroot><mn>2</mn><mrow><mi>p</mi><mi>p</mi><mi>p</mi></mrow></mroot></math>`,
    `<math><msqrt><mfenced><mfenced open="|" close="|"><mfenced open="&lt;" close="&gt;"><mfenced open="[" close="]"><mfenced open="||" close="||"><mfenced open="{" close="}"><mfenced open="&#x230A;" close="&#x230B;"><mfenced open="&#x2308;" close="&#x2309;"><mrow/></mfenced></mfenced></mfenced></mfenced></mfenced></mfenced></mfenced></mfenced></msqrt><mo>&#xA0;</mo><msqrt><mo>(</mo><mo>|</mo><mo>[</mo><mo>{</mo><mo>}</mo><mo>]</mo><mo>|</mo><mo>)</mo></msqrt></math>`,
    `<math><msub><mi>Q</mi><mi>n</mi></msub><mo>&#xA0;</mo><msup><mi>P</mi><mi>j</mi></msup><mo>&#xA0;</mo><mmultiscripts><mi>W</mi><none/><mi>j</mi><mprescripts/><mi>p</mi><mi>p</mi></mmultiscripts><mo>&#xA0;</mo><msup><mi>f</mi><mi>g</mi></msup></math>`,
    `<math><mo>(</mo><mi>f</mi><mo>+</mo><mi>f</mi><mo>)</mo><mfenced><mrow><mi>W</mi><mo>,</mo><mi>T</mi></mrow></mfenced><mfenced><mmultiscripts><mi>U</mi><mi>Q</mi><mi>T</mi><mprescripts/><mi>M</mi><mi>N</mi></mmultiscripts></mfenced></math>`,
    `<math><msub><mfenced><mi>x</mi></mfenced><mi>w</mi></msub><mo>(</mo><mi>x</mi><msup><mo>)</mo><mi>j</mi></msup></math>`,
    `<math><munder><munder><mrow><mi>f</mi><mo>(</mo><mi>x</mi><mo>)</mo></mrow><mo>&#x23DF;</mo></munder><mrow><mi>y</mi><mo>=</mo><msup><mi>x</mi><mn>2</mn></msup></mrow></munder><mo>&#x2218;</mo><mover><mover><mrow><mi>g</mi><mo>(</mo><mi>x</mi><mo>)</mo></mrow><mo>&#x23DE;</mo></mover><mrow><mi>y</mi><mo>=</mo><msub><mi>a</mi><mi>j</mi></msub></mrow></mover><mo>&#xA0;</mo><mo>&#xA0;</mo></math>`,
    `<math xmlns="http://www.w3.org/1998/Math/MathML"><mo mathvariant="bold" mathcolor="#7F0000" mathsize="48px">&#xAB;</mo><mo mathvariant="bold" mathcolor="#7F0000" mathsize="48px">&lt;</mo><mo mathvariant="bold" mathcolor="#7F0000" mathsize="48px">&#xBB;</mo><mo mathvariant="bold" mathcolor="#7F0000" mathsize="48px">&gt;</mo><mo mathvariant="bold" mathcolor="#7F0000" mathsize="48px">&#xA7;</mo><mo mathvariant="bold" mathcolor="#7F0000" mathsize="48px">&amp;</mo><mo mathvariant="bold" mathcolor="#7F0000" mathsize="48px">&#xA8;</mo><mo mathvariant="bold" mathcolor="#7F0000" mathsize="48px">&quot;</mo><mo mathvariant="bold" mathcolor="#7F0000" mathsize="48px">'</mo><mo mathvariant="bold" mathcolor="#7F0000" mathsize="48px">'</mo></math>`,
  ];

  /**
   * This test suite validates the functionality of the `serializeHtmlToXml` function.
   * The function is expected to convert valid HTML into valid XML.
   *
   * Each test case follows these steps:
   * 1. An input HTML string is passed to the `serializeHtmlToXml` function, which returns an XML string.
   * 2. The XML string is parsed as text/xml using the DOMParser's.
   * 3. The parsed XML document is checked for `parsererror` nodes.
   *
   * If the XML document contains any `parsererror` nodes, it indicates that the `serializeHtmlToXml` function
   * did not correctly convert the HTML to valid XML, causing the DOMParser to encounter errors during parsing.
   * In this case, the test will fail.
   *
   * If no `parsererror` nodes are found, it indicates that the `serializeHtmlToXml` function correctly converted
   * the HTML to valid XML, and the test will pass.
   */
  testCases.forEach((input, index) => {
    it(`Test ${index}: ${input.slice(0, 40)} ...`, () => {
      const parser = new global.DOMParser();
      const output = serializeHtmlToXml(input);
      const parsed = parser.parseFromString(output, "text/xml");
      let errorNodes = parsed.getElementsByTagName("parsererror");
      expect(errorNodes.length).toBe(0);
    });
  });
});
