# This is a sample workflow for Cypress.
# It setups the environment and uses a cache for better performance on node and Cypress.
# This action is based on the Kitchen Sink project (https://github.com/cypress-io/cypress-example-kitchensink/)
# It can run tests by Browser and test file selection.

name: Run Cypress tests without cache

on: 
  - push
  - workflow_dispatch

jobs:

  setup-cypress:
    name: Setup and start the default app
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      # 01. install a specific version of Node using
      # https://github.com/actions/setup-node
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      # 05. Install dependencies and verify Cypress
      - name: Install dependencies and verify Cypress
        env:
          # make sure every Cypress install prints minimal information
          CI: 1
        # print Cypress and OS info
        # This next command should use "npm ci" instead of "npm install"
        run: |
          npm ci
          npx cypress verify
          npx cypress info
          npx cypress version
          npx cypress version --component package
          npx cypress version --component binary
          npx cypress version --component electron
          npx cypress version --component node

  run-all-tests-matrix:
    runs-on: ubuntu-18.04

    needs: setup-cypress

    strategy:
      fail-fast: true
      matrix:
        # Define values for browsers from
        browser: ["chrome"]
        # browser: ["chrome", "edge", "firefox", "chromium"]
        type: ["all"]
        # type: ["smoke","e2e", "ui", "validation"]

    name: Run ${{ matrix.type }} tests on ${{ matrix.browser }}

    steps:
      - uses: actions/checkout@master

      - name: Checkout
        uses: actions/checkout@v2
    
      # install a specific version of Node using
      # https://github.com/actions/setup-node
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Run tests by browser
        uses: cypress-io/github-action@v2
        timeout-minutes: 10
        with:
          # 'build' starts the defauld demo 
          build: npm run build
          # 'test:ci' runs tests over Docker image for build context 
          command: npm run test:ci
          record: false
          parallel: false
          group: "${{ matrix.type }} tests on ${{ matrix.browser }}"
          browser: ${{ matrix.browser }}
          config: "video: true"
          spec: |
            cypress/tests/**/*.js
          # config: "\"video\": true, \"screenshotsFolder\": \"cypress/screenshots/${{ matrix.browser }}\", \"videosFolder\": \"cypress/videos/${{ matrix.browser }}\", \"video\": true"
          # spec: cypress/tests/${{ matrix.type }}/*.js
        # env:
        # https://github.com/cypress-io/cypress-example-kitchensink/settings/secrets
            # screenshotsFolder: "cypress/screenshots/${{ matrix.browser }}"
            # videosFolder: "cypress/videos/${{ matrix.browser }}"
        #   TERM: xterm
        #   CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
        #   CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      # Save videos and screenshots as test artifacts
      # https://github.com/actions/upload-artifact
      - name: Upload screenshots
        uses: actions/upload-artifact@master
        # there might be no screenshots created when:
        # - there are no test failures
        # so only upload screenshots if previous step has failed
        if: failure()
        with:
          name: screenshots-${{ matrix.type }}-${{ matrix.browser }}
          path: cypress/screenshots
      # video should always be generated
      - name: Upload videos for all tests
        uses: actions/upload-artifact@master
        with:
          name: videos-${{ matrix.type }}-${{ matrix.browser }}
          path: cypress/videos
