# It runs all available Cypress tests and sends test data to Cypress Dashboard.
# It executes on every Monday at 01 a.m, and on demand by the user.
# The tests run with a fail-fast strategy, once one fails, the others will not run.
# If a test fails, it creates a set of screenshots showing the errors.
#
# Matrix:
# - Browser: chrome.
# - Test folder: All tests available on the `/tests` folder.
#
# Jobs:
# - Set up the Cypress Environment: `setup-cypress`.
# - Runs all tests on the matrix: `run-all-tests-matrix`.

name: Run Cypress tests with npm or local packages

on:
  push:
  pull_request:
    types: [ opened, reopened]
  schedule:
    # runs every Monday at 1 a.m
    - cron: '0 1 * * 1'
      filters:
        branches:
          only:
            - stable
  workflow_dispatch:
    inputs:
      # Sends data to Cypress Dashboard
      cypress-record:
        description: Send test data to Cypress Dashboard? Write 'Yes' to send data.
        required: true
        default: 'No'
      packages-code:
        # This input requires its parameters to be written in single quotes.
        description: |
          List of where to take the package's code from, 'local' is the current only option.
          * Note that if you write any different value than the accepted ones, or use double quotes, the workflow will fail.
        required: true
        default: "['local']"

jobs:
  setup-cypress:
    # Setup Cypress environment without cache.
    name: Setup Cypress environment without cache
    runs-on: ubuntu-latest
    steps:
      # 01. Checkout the repository.
      - name: Checkout
        uses: actions/checkout@v2

      # 02. Install a specific version of Node using.
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      # 03. Install dependencies and verify Cypress
      - name: Install dependencies and verify Cypress
        env:
          # make sure every Cypress install prints minimal information
          CI: 1
        # print Cypress and OS info
        # This next command should use "npm ci" instead of "npm install"
        run: |
          npm ci
          npx cypress verify
          npx cypress info
          npx cypress version
          npx cypress version --component package
          npx cypress version --component binary
          npx cypress version --component electron
          npx cypress version --component node

  # This job will expose to the workflow a variable containing the data
  # of where to take the packages code from (local or public)
  # in order to use it as a part of the matrix strategy when running the tests
  define-env:
    runs-on: ubuntu-latest
    needs: setup-cypress

    name: Define run environment

    steps:

      # 01a. Decide whether to run the tests with local or publish packages, on push or pull request
      - name: Set local environment to run tests for push and pull request
        if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
        run: |
          echo "TESTS_ENV=['local']" >> $GITHUB_ENV

      # 01b. Decide whether to run the tests with local or publish packages, on workflow dispatch
      - name: Set the environment to run the tests defined by the user
        if: ${{ github.event.inputs.packages-code != '' }}
        run: |
          echo "TESTS_ENV=${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      # 01c. Decide whether to run the tests with local or publish packages, on schedule
      - name: Schedule the tests to run with published packages monthly
        if: ${{ github.event_name == 'schedule' }}
        run: |
          echo "TESTS_ENV=['local']" >> $GITHUB_ENV
      
      # 02. Export the previously defined environment variable to the job
      - name: Export environment for test run
        # Then, this job will be able to expose the variable to the workflow, and then, another job will be able to use it
        id: export-matrix-env
        run: |
          echo "::set-output name=tests_env::${{env.TESTS_ENV}}"

    # Export the variable that specifies where to take the package's code from,
    # to be used in the matrix for the testing strategy.
    # This variable will be visible for all the jobs on this workflow.
    outputs:
      tests-env: ${{ steps.export-matrix-env.outputs.tests_env }}

  run-all-tests-matrix:
    # Runs all tests.
    runs-on: ubuntu-latest
    needs: define-env

    strategy:
      fail-fast: true
      matrix:
        # Define values for browsers from
        browser: ['chrome']
        # browser: ['chrome', 'edge', 'firefox', 'chromium']
        type: ['all']
        # type: ['smoke','e2e', 'ui', 'validation']
        env: ${{ fromJson(needs.define-env.outputs.tests-env) }} # where to take packages code from
        # env: ['local', 'public']

    name: Run ${{ matrix.type }} tests on ${{ matrix.browser }} with ${{ matrix.env }} packages
    steps:
      # 01. Checkout the repository.
      - name: Checkout
        uses: actions/checkout@v2

      # 02. Install a specific version of Node.
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      # 03a. Decide whether to send data to Cypress Dashboard, or not, for workflow_dispatch, schedule and pull request.
      - name: Decide if we send data to Cypress 2
        if: ${{ github.event.inputs.cypress-record == 'Yes' || github.event_name == 'schedule' || github.event_name == 'pull_request' }}
        run: |
          echo "CY_RECORD_KEY=${{ secrets.CYPRESS_RECORD_KEY }}" >> $GITHUB_ENV
          echo "CY_RECORD_FLAG=-- --record --key " >> $GITHUB_ENV

      # 03b. Decide whether to send data to Cypress Dashboard, or not, for workflow_dispatch and push.
      - name: Decide if we send data to Cypress 1
        # We don't want to send the tests to Dashboard through workflow dispatch
        if: ${{ github.event.inputs.cypress-record != 'Yes' || github.event_name == 'push' }}
        # we set the environment variables dynamically to empty in order to avoid
        # recording the test execution to Cypress Dashboard.
        run: |
          echo "CY_RECORD_KEY=" >> $GITHUB_ENV
          echo "CY_RECORD_FLAG=" >> $GITHUB_ENV

      # 04. Install Lerna dependencies when running tests with local packages
      - name: Install dependencies for local packages
        # add demos to lerna.json file and install lerna dependencies on the project root
        # It requires a step in order to ensure that the dependencies are properly installed
        # and does not give issues with Lerna and cypress
        if: ${{ matrix.env == 'local' }}
        run: |
          npm ci
          cp lerna.demos.json lerna.json
          npx lerna exec -- npm i

      # 05. Run the tests following the initial matrix: by browser and test type
      - name: Run ${{ matrix.type }} tests on $${{ matrix.browser }} with ${{ matrix.env }} packages
        uses: cypress-io/github-action@v2
        timeout-minutes: 10
        with:
          # 'build' starts the default demo
          # use the env matrix variable to know if the test should run with local or public packages
          build: npm run build-generic-demo:${{ matrix.env }}
          # 'test:ci' runs tests over Docker image for build context
          # we also send the Cypress Dashboard record key dynamically
          command: npm run test:ci ${{ env.CY_RECORD_FLAG }} ${{ env.CY_RECORD_KEY }}
          record: true
          parallel: true
          group: "${{ matrix.type }} tests on ${{ matrix.browser }}"
          browser: ${{ matrix.browser }}
          config: "video: true"
          spec: |
            cypress/tests/**/*.js
        env:
          # https://github.com/wiris/html-integrations/settings/secrets/actions
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GH_CICD_TOKEN }}

      # 06a. Save videos and screenshots as test artifacts
      # https://github.com/actions/upload-artifact
      - name: Upload screenshots
        uses: actions/upload-artifact@master
        # there might be no screenshots created when:
        # - there are no test failures
        # so only upload screenshots if previous step has failed
        if: failure()
        with:
          name: screenshots-${{ matrix.type }}-${{ matrix.browser }}
          path: cypress/screenshots

      # 06b. Upload videos, since they are always generated.
      - name: Upload videos for all tests
        uses: actions/upload-artifact@master
        with:
          name: videos-${{ matrix.type }}-${{ matrix.browser }}
          path: cypress/videos
