# Publishes the MathType integrations WordPress packages to AWS S3
#
# Jobs:
# - Publish Wordpress
#
name: Publish WordPress

# Controls when the action will run
on:
  workflow_dispatch:
    inputs:
      publish_aws:
        description: |
          Whether to publish the generated artifacts to S3.
          Type `publish_aws` to do publish to S3, any other value otherwise.
        required: false
        default: ""
